In [3]:
import pandas as pd

In [25]:
df = pd.read_csv('GSE161824_A549_KRAS.variants2cell.csv',sep='\t')

In [26]:
df

,batch,n_counts,T20R,T158T,M111L,V112I,T50I,G13C,Q22H,L159S,...,S136N,E63K,I36M,A59T,A155G,A66A,T144T,variant,variant.detailed_multi,cell
0,0,25694.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,unassigned,unassigned,AAACCTGCAACGCACC-1-0
1,0,34868.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T50T,T50T,AAACCTGCAATGGTCT-1-0
2,0,25170.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,unassigned,unassigned,AAACCTGCAGGACGTA-1-0
3,0,31500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,unassigned,unassigned,AAACCTGCAGTAAGAT-1-0
4,0,22654.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T127T,T127T,AAACGGGAGACAGAGA-1-0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150039,31,15471.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,M170L,M170L,TTTGTCAAGAGGGCTT-1-31
150040,31,21986.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Q99E,Q99E,TTTGTCAAGGGATACC-1-31
150041,31,17064.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,G13R,G13R,TTTGTCACACATGACT-1-31
150042,31,23769.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Y166H,Y166H,TTTGTCACAGAAGCAC-1-31
150043,31,24162.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T20R,T20R,TTTGTCATCCGAATGT-1-31

In [27]:
df = df[['variant.detailed_multi','cell']].copy()
df

       variant.detailed_multi                   cell
0                  unassigned   AAACCTGCAACGCACC-1-0
1                        T50T   AAACCTGCAATGGTCT-1-0
2                  unassigned   AAACCTGCAGGACGTA-1-0
3                  unassigned   AAACCTGCAGTAAGAT-1-0
4                       T127T   AAACGGGAGACAGAGA-1-0
...                       ...                    ...
150039                  M170L  TTTGTCAAGAGGGCTT-1-31
150040                   Q99E  TTTGTCAAGGGATACC-1-31
150041                   G13R  TTTGTCACACATGACT-1-31
150042                  Y166H  TTTGTCACAGAAGCAC-1-31
150043                   T20R  TTTGTCATCCGAATGT-1-31

[150044 rows x 2 columns]

In [28]:
def split_and_expand(row):
    # Split the values in the second column by '|'
    values_to_split = row['variant.detailed_multi'].split(',')
    
    # Create a new row for each split value, while keeping the value in the first column the same
    return pd.DataFrame({'cell': [row['cell']] * len(values_to_split),
                         'variant.detailed_multi': values_to_split})

In [29]:
expanded_rows = pd.concat(df.apply(split_and_expand, axis=1).to_list(), ignore_index=True)

In [30]:
expanded_rows

                         cell variant.detailed_multi
0        AAACCTGCAACGCACC-1-0             unassigned
1        AAACCTGCAATGGTCT-1-0                   T50T
2        AAACCTGCAGGACGTA-1-0             unassigned
3        AAACCTGCAGTAAGAT-1-0             unassigned
4        AAACGGGAGACAGAGA-1-0                  T127T
...                       ...                    ...
163897  TTTGTCAAGAGGGCTT-1-31                  M170L
163898  TTTGTCAAGGGATACC-1-31                   Q99E
163899  TTTGTCACACATGACT-1-31                   G13R
163900  TTTGTCACAGAAGCAC-1-31                  Y166H
163901  TTTGTCATCCGAATGT-1-31                   T20R

[163902 rows x 2 columns]

In [31]:
expanded_rows['guide_identity'] = 'KRAS_' + expanded_rows['variant.detailed_multi']

In [32]:
expanded_rows['cell_barcode'] = expanded_rows['cell'].copy()

In [33]:
expanded_rows['gene'] = 'KRAS'

In [34]:
expanded_rows['BioSample_ID'] = 'PRJNA679579'

In [35]:
expanded_rows

,cell,variant.detailed_multi,guide_identity,cell_barcode,gene,BioSample_ID
0,AAACCTGCAACGCACC-1-0,unassigned,KRAS_unassigned,AAACCTGCAACGCACC-1-0,KRAS,PRJNA679579
1,AAACCTGCAATGGTCT-1-0,T50T,KRAS_T50T,AAACCTGCAATGGTCT-1-0,KRAS,PRJNA679579
2,AAACCTGCAGGACGTA-1-0,unassigned,KRAS_unassigned,AAACCTGCAGGACGTA-1-0,KRAS,PRJNA679579
3,AAACCTGCAGTAAGAT-1-0,unassigned,KRAS_unassigned,AAACCTGCAGTAAGAT-1-0,KRAS,PRJNA679579
4,AAACGGGAGACAGAGA-1-0,T127T,KRAS_T127T,AAACGGGAGACAGAGA-1-0,KRAS,PRJNA679579
...,...,...,...,...,...,...
163897,TTTGTCAAGAGGGCTT-1-31,M170L,KRAS_M170L,TTTGTCAAGAGGGCTT-1-31,KRAS,PRJNA679579
163898,TTTGTCAAGGGATACC-1-31,Q99E,KRAS_Q99E,TTTGTCAAGGGATACC-1-31,KRAS,PRJNA679579
163899,TTTGTCACACATGACT-1-31,G13R,KRAS_G13R,TTTGTCACACATGACT-1-31,KRAS,PRJNA679579
163900,TTTGTCACAGAAGCAC-1-31,Y166H,KRAS_Y166H,TTTGTCACAGAAGCAC-1-31,KRAS,PRJNA679579
163901,TTTGTCATCCGAATGT-1-31,T20R,KRAS_T20R,TTTGTCATCCGAATGT-1-31,KRAS,PRJNA679579

In [36]:
df_1 = expanded_rows[['gene','guide_identity','cell_barcode','BioSample_ID']].copy()

In [23]:
#df_tot = df_1.copy()

In [37]:
df_tot = pd.concat([df_tot,df_1])

In [4]:
df_tot = pd.read_csv('PRJNA679579_mapping.csv')

In [7]:
df_tot = df_tot.drop(columns='Unnamed: 0')

In [8]:
df_tot.to_csv('PRJNA679579_mapping.csv',index=False)